spring:
  datasource:
    url: jdbc:mysql://localhost:3306/megacgv?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: root

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secretKey: LOCAL_JWT_SECRET_KEY_ON_MEGA_CGV_PROJECT_BY_GISUNG
  access:
    expiration: 1800000
  refresh:
    expiration: 1209600000